import { NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';

const API_SECRET = process.env.MYARK_API_SECRET || 'fallback-secret-for-now';

export async function GET(req: Request) {
  const supabaseAdmin = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY || 'placeholder'
  );

  // 1. Authenticate Request
  const authHeader = req.headers.get('Authorization');
  if (authHeader !== `Bearer ${API_SECRET}`) {
    return NextResponse.json({ error: 'Unauthorized: Invalid API Key' }, { status: 401 });
  }

  try {
    const { searchParams } = new URL(req.url);
    const url = searchParams.get('url');
    const title = searchParams.get('title');

    // Case 1: Search for specific existence
    if (url || title) {
      let query = supabaseAdmin
        .from('opportunities')
        .select('id, title, slug, registration_url');

      if (url) {
        query = query.eq('registration_url', url);
      }
      
      if (title) {
        query = query.ilike('title', title);
      }

      const { data, error } = await query.maybeSingle();

      if (error) {
        return NextResponse.json({ error: error.message }, { status: 500 });
      }

      return NextResponse.json({
        exists: !!data,
        opportunity: data || null
      });
    }

    // Case 2: List current opportunities (Recent)
    const { data: opportunities, error } = await supabaseAdmin
      .from('opportunities')
      .select('id, title, slug, registration_url, created_at')
      .order('created_at', { ascending: false })
      .limit(50);

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json({
      opportunities
    });

  } catch (err) {
    console.error('Unhandled GET API Error:', err);
    return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
  }
}

export async function POST(req: Request) {
  // Initialize Supabase ONLY when called to avoid build-time errors
  const supabaseAdmin = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY || 'placeholder'
  );

  // 1. Authenticate Request
  const authHeader = req.headers.get('Authorization');
  if (authHeader !== `Bearer ${API_SECRET}`) {
    return NextResponse.json({ error: 'Unauthorized: Invalid API Key' }, { status: 401 });
  }

  try {
    const payload = await req.json();

    // 2. Validate Minimum Fields
    if (!payload.title || !payload.sourceUrl) {
      return NextResponse.json({ error: 'Missing required fields: title or sourceUrl' }, { status: 400 });
    }

    // 2.5 Check for existing by sourceUrl (Prevent direct Duplicates)
    const { data: existing } = await supabaseAdmin
      .from('opportunities')
      .select('id')
      .eq('registration_url', payload.sourceUrl)
      .maybeSingle();

    if (existing) {
       return NextResponse.json({ 
         success: false, 
         message: 'Opportunity already exists',
         id: existing.id
       }, { status: 409 });
    }

    // 3. Transform Scanner Data to Myark Database Structure
    // Generate Slug from Title
    const slug = payload.title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '') + '-' + Math.floor(Math.random() * 1000);

    // Find or handle Organiser 
    // (In This phase, we'll store organiser name as text or try to find a match)
    const { data: orgMatch } = await supabaseAdmin
      .from('organisers')
      .select('id')
      .ilike('name', payload.organizer)
      .maybeSingle();

    let organiser_id = orgMatch?.id;

    // If no organiser, we'll create one as a placeholder or use a default "Uncategorized Organiser"
    if (!organiser_id && payload.organizer) {
      const { data: newOrg } = await supabaseAdmin
        .from('organisers')
        .insert({ 
           name: payload.organizer, 
           slug: payload.organizer.toLowerCase().replace(/[^a-z0-9]+/g, '-') 
        })
        .select('id')
        .single();
      organiser_id = newOrg?.id;
    }

    // Find Category Match (Defaulting to 'Scholarship' if none)
    const { data: catMatch } = await supabaseAdmin
      .from('categories')
      .select('id')
      .eq('label', 'Scholarship')
      .single();

    const opportunityData = {
      title: payload.title,
      slug: slug,
      organiser_id: organiser_id,
      category_id: catMatch?.id,
      description: payload.prizes ? `Prizes: ${payload.prizes}` : 'Generated by AI Scanner.',
      eligibility_text: payload.eligibility || '',
      fee_text: payload.fees || 'Free',
      registration_url: payload.sourceUrl,
      deadline_tentative: payload.deadlines || '',
      how_to_apply: payload.applicationSteps || '',
      is_published: false, // For manual review
      is_verified: false,
      faqs: [],
      // Storing metadata for review
      confidence_score: payload.confidenceScore,
      confidence_reasoning: payload.confidenceReasoning
    };

    // 4. Insert into Database
    const { data: newOpportunity, error } = await supabaseAdmin
      .from('opportunities')
      .insert(opportunityData)
      .select('id')
      .single();

    if (error) {
      console.error('Push Error:', error);
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json({ 
      success: true, 
      message: 'Opportunity successfully pushed to Myark (Published: False)',
      id: newOpportunity.id
    });

  } catch (err) {
    console.error('Unhandled Push API Error:', err);
    return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
  }
}
